### ISSUE TITLE
WebSocketException when trying to connect to lavalink 

### ISSUE THREAD

**Issue by Schedarian** [nyxx-discord/nyxx_lavalink#6]
Hello!
Encountered this exception after updating nyxx and nyxx_lavalink to version 3.x.x

Whenever the client tries to connect it throws this:
```
[2022-01-24 02:52:05.036827] [INFO] [Lavalink] [Node 1] Trying to connect to lavalink (2/5)
[2022-01-24 02:52:05.039550] [WARNING] [Lavalink] [Node 1] Error while trying to connect to lavalink; WebSocketException: Connection to 'http://127.0.0.1:2333# was not upgraded to websocket
[2022-01-24 02:52:05.039572] [WARNING] [Lavalink] [Node 1] Failed to connect to lavalink, retrying
```

And hence lavalink throws this:
```
2022-01-24 02:52:05.500 ERROR 39839 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /127.0.0.1:43452
2022-01-24 02:52:10.859 ERROR 39839 --- [  XNIO-1 task-2] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /127.0.0.1:43536
```

Never encountered this problem before updating nyxx.
IP, port and password match for sure as I'm loading NodeOptions() options right from the application.yml 

`netstat -tulpn | grep LISTEN` shows that lavalink is running normally:

`tcp6       0      0 127.0.0.1:2333          :::*                    LISTEN      43987/java`

application.yml:
```
server:
  port: 2333
  address: 127.0.0.1
lavalink:
  server:
    password: 'secret'
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: false
```
os: ubuntu 20.04 lts, kernel 5.4.0-96-generic
dart: 2.15.1
nyxx: 3.2.4
nyxx_lavalink: 3.0.1

Can this be some internal problem or, perhaps, I'm doing something wrong?
